- name: "Install Engagefront dependencies"
  hosts: newengagefront1
  become: yes
  become_method: sudo

  tasks:

    - name: Adding repo for recent redis
      shell: add-apt-repository -y ppa:chris-lea/redis-server; apt-get update;

    - name: install base packages
      apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
      with_items:
        - graphicsmagick
        - redis-server 
