- name: "Pull down relevant Git repos for Engagefron, create some symlinks and stuff too"
  hosts: newengagefront1
  become: yes
  become_method: sudo

  tasks:

    - name: Clone Rolloutconsole repo
      git:
        repo: "ssh://git@github.com/amoa/rolloutconsole.git"
        dest: /tmp/rolloutconsole
        accept_hostkey: yes
      delegate_to: "{{ groups['cnc'][0] }}"
      become_user: byron

    - name: sync proj to destination
      synchronize:
        src: "/tmp/rolloutconsole"
        dest: "/opt/rolloutconsole"
        recursive: yes
        rsync_opts:
          - "--no-motd"
          - "--exclude=.git"    
        

        #      - name: Link to rollout console and create /var/sites
        #        shell: ln -s /opt/rolloutconsole /var/sites/rollout 
                     
        #      - name: Copy rollout console config file
        #      - shell: cp -f /opt/rolloutconsole/init/rollout.conf  /etc/init/rollout.conf
